### ISSUE TITLE
Need C2_W4 file

### ISSUE THREAD

**Issue by Divyam6969** [troncosomath/NLP-Specialization#1]
Can you please upload c2_w4 file

**Comment by troncosomath** [comment]
Thanks for reaching out @Divyam6969. I will be uploading the files on 04-20-2024 together with that I will be updating the Readme file with the 10,000 feet high level overview of the course and the readme file of the course with my personal notes on the course week by week. If you like the material  a ⭐ is highly appreciated

**Comment by troncosomath** [comment]
Fixed
